### ISSUE TITLE
My first release, a help request

### ISSUE THREAD

**Issue by stappersg** [pusherofbrooms/avr-delay#19]
I'm new to the workflow of a release,  I'm asking for help.

Goal is the actual switch from `llvm_asm!` to `asm!`. 

[actual switch](#18) and [version bump](https://github.com/avr-rust/delay/commit/398d435e72e1c4c676bf48ab16382ccfd88649e5) have been done.

The failed CI run for [Fix build: Use the new rust asm! available in rustc 1.63.0-nightly](https://github.com/avr-rust/ruduino/pull/43) indicates something extra needs to be done.  Maybe something like adding a _git tag_ or sending some trigger signal.

What should I do next?

**Comment by stappersg** [comment]
FYI
```text
$ git push --tags
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:avr-rust/delay.git
 * [new tag]         0.4.0 -> 0.4.0
$
```

**Comment by mbuesch** [comment]
The build bot says
```
error[E0472]: asm! is unsupported on this target
```

Is it using an older version of rustc? Only the very latest rust nightly has fixed AVR8 support plus all new features like asm! macro.

**Comment by mbuesch** [comment]
```
Step 6/11 : RUN wget -q https://sh.rustup.rs/ -O /tmp/rustup.sh && sh /tmp/rustup.sh -y --profile minimal --default-toolchain nightly-2021-01-05 -c rust-src --quiet
```

That's too old.

That was the last release before they broke AVR8 support. But it has been fixed now, so an upgrade of the compiler can (should) be done.

**Comment by stappersg** [comment]
Yes, we could also be bitten by an old version.  We will deal with it in another issue.

For releasing `avr_delay` I report:
```text
$ cargo publish
    Updating crates.io index
error: no upload token found, please run `cargo login` or pass `--token`
$
```

AFAIK I have no _cargo credentials_,   I will persuit them.

Those who are more comfortable with `cargo publish`:
Are _cargo logins_ and _crates_ coupled?
Incase of _yes, they are_:  How to add an account to a crate?

**Comment by mbuesch** [comment]
The owner of a crate can add other owners to the crate in the crate's settings on crates.io (github login).

**Comment by stappersg** [comment]
> The owner of a crate can add other owners to the crate in the crate's settings on crates.io (github login).

Ah, thanks @mbuesch  and high-lighting @dylanmckay for further awareness on the pending request.

![afbeelding](https://user-images.githubusercontent.com/35434094/169646525-beace466-d935-4ddb-b543-7666f174980e.png)

**Comment by n8henrie** [comment]
One common option here, especially since you're already using GitHub Actions for CI, would be to also leverage it to publish to crates.io upon pushing a new tag. You'd need to set up an API token as a shared secret (which can be either specific to this repo, or to the avr-rust org as a whole).

Something like this might work:

```
on:
  push:
    tags:
      - '*'
  name: Publish to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rust-src
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token {{ "${{ secrets.CARGO_API_KEY " }}}}
```

If you're interested, I'd be happy to work on PRs to this effect, both for this repo as well as https://github.com/avr-rust/ruduino/
